version: "3.8"

services:
  model:
    build:
      context: .
      dockerfile: docker/model/Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONPATH=/app
    volumes:
      - ./model:/app/model
      - ./config:/app/config
    working_dir: /app/model
    container_name: goemotions-model
    command: ["sleep", "infinity"]

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - model
    volumes:
      - ./api:/app/api
      - ./model:/app/model
      - ./config:/app/config
    working_dir: /app
    container_name: goemotions-api

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: goemotions-client
    ports:
      - "3000:80"
    depends_on:
      - api
    volumes:
      - ./client:/app/client
    working_dir: /app/client