services:
  model:
    build:
      context: .
      dockerfile: docker/Dockerfile.model
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONPATH=/app
    volumes:
      - ./app/model:/app/model
      - ./app/config:/app/config
      - ./data:/app/data
      - ./model/models:/app/model/models  # volume condiviso
    working_dir: /app/model
    container_name: goemotions-model
    command: ["sleep", "infinity"]

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    depends_on:
      - model
    volumes:
      - ./app:/app
      - ./data:/app/data
      - ./model/models:/app/model/models  # volume condiviso
    working_dir: /app
    container_name: goemotions-api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: goemotions-client
    ports:
      - "3000:80"
    depends_on:
      - api
    volumes:
      - ./client:/app/client
    working_dir: /app/client
