# config.yaml – configurazione centralizzata per tutto il progetto

model:
  name: "microsoft/deberta-v3-base"
  dir: "model/models"
  num_labels: 27  # oppure 28 se includi 'neutral'
  max_length: 128
  seed: 42

training:
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 32
  num_train_epochs: 8
  learning_rate: 1e-5
  warmup_steps: 500
  weight_decay: 0.01
  lr_scheduler_type: "cosine"
  evaluation_strategy: "steps"
  eval_steps: 500
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 2
  logging_steps: 100
  fp16: true
  load_best_model_at_end: true
  metric_for_best_model: "f1_micro"
  greater_is_better: true
  dataloader_num_workers: 4
  report_to: "none"
  output_dir: "model/models"

thresholding:
  default_threshold: 0.5
  thresholds_path: "model/models/best_thresholds.json"
  batch_size: 32               # batch usato per calcolare i thresholds
  threshold_range:             # intervallo da esplorare per ciascun label
    start: 0.1
    stop: 0.9
    step: 0.05


labels:
  include_neutral: false
  list:
    - "admiration"
    - "amusement"
    - "anger"
    - "annoyance"
    - "approval"
    - "caring"
    - "confusion"
    - "curiosity"
    - "desire"
    - "disappointment"
    - "disapproval"
    - "disgust"
    - "embarrassment"
    - "excitement"
    - "fear"
    - "gratitude"
    - "grief"
    - "joy"
    - "love"
    - "nervousness"
    - "optimism"
    - "pride"
    - "realization"
    - "relief"
    - "remorse"
    - "sadness"
    - "surprise"
    - "neutral"

sentiment:
  positive:
    - "joy"
    - "love"
    - "gratitude"
    - "relief"
    - "amusement"
    - "optimism"
    - "admiration"
    - "pride"
    - "approval"
    - "caring"
    - "excitement"
    - "contentment"
  negative:
    - "anger"
    - "fear"
    - "sadness"
    - "disappointment"
    - "disgust"
    - "remorse"
    - "grief"
    - "annoyance"
    - "disapproval"
    - "embarrassment"
    - "nervousness"
  neutral:
    - "realization"
    - "curiosity"
    - "confusion"
    - "surprise"

api:
  host: "0.0.0.0"
  port: 8000

surrogate:
  n_perturbations: 25
  threshold: 0.5
  max_depth: 3

paths:
  data_dir: "data"
  raw_data_dir: "data/raw"
  tokenized_data_dir: "data/processed"
  dataset: "data/goemotions.csv"  # Puoi anche rimuoverlo se non lo usi più
  logs: "model/logs"
  metrics_file: "logs/eval_with_thresholds.json"
  metrics_csv: "logs/eval_with_thresholds_metrics.csv"

