FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

# Directory di lavoro coerente per tutto
WORKDIR /app

# Requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Download risorse NLTK
RUN python -m nltk.downloader wordnet omw-1.4 averaged_perceptron_tagger averaged_perceptron_tagger_eng stopwords

#COPY app/config ./app/config
#COPY app/api ./app/api
#COPY app/utils ./app/utils

# 🔧 Entry point di default
CMD ["python"]
# Avvio dell'applicazione API